# Generated by Django 3.2.7 on 2022-04-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_going',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_image', models.ImageField(upload_to='event_images')),
            ],
        ),
    ]
