# Generated by Django 3.2.7 on 2022-04-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_events_going'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='image2',
        ),
    ]
